name: 'Check oldstable'
description: 'Check if version of go directive in go.mod is oldstable.'
branding:
  icon: 'check'
  color: 'gray-dark'
inputs:
  github-token:
    description: The GitHub token
    default: ${{ github.token }}
    required: false
  go-mod-file:
    description: The path to go.mod file
    default: 'go.mod'
    required: false
  lax:
    description: 'If true, allow oldstable version or older (error only on stable version).'
    default: false
    required: false
runs:
  using: "composite"
  steps:
    -
      uses: k1LoW/gh-setup@v1
      with:
          github-token: ${{ inputs.github-token }}
          repo: k1LoW/oldstable
    -
      run: oldstable ${{ inputs.go-mod-file }} ${{ inputs.lax && '--lax' || '' }}
      shell: bash
